souslesens/souslesensVocables

- .github/workflows/build-docker-images.yaml
- master branch
- PR on master branch
- tag
> Github action: build docker image

- mainapp/lib/Component/ButtonWithConfirmation.d.ts
- mainapp/src/Component/ButtonWithConfirmation.tsx
- mainapp/src/Component/ProfilesTable.tsx
- mainapp/src/Component/SourcesTable.tsx
- mainapp/src/Component/UsersTable.tsx
- package-lock.json
- package.json
- feat(admin): Asks confirmation before deleting ressource
- chore: update npm packages
> Confirm de button

- .eslintrc.js
- model/users.js
- package-lock.json
- package.json
- tests/model.users.test.js
- tsconfig.json
Here are some fixes and improvements on the changes you made this morning. :)
> Review of model/users.js and tests changes

- api/v1/paths/kg/clearGraph.js
- api/v1/paths/kg/csv/triples.js
- api/v1/paths/kg/graph/{graphUri}.js
- legacy_routes.js
- public/vocables/js/tools/KGcreator.js
Add the last kgendpoints to openapi
> Kg endpoints openapi

- api/v1/paths/admin/ontology/{id}.js
- api/v1/paths/httpProxy.js
- api/v1/paths/pluginController/jsonFile.js
- api/v1/paths/utils.js
- cypress/integration/lineage.spec.js
- legacy_routes.js
- public/vocables/js/customPluginController.js
- public/vocables/js/tools/admin.js
This PR moves get httpProxy, get ontology, get jsonFile to open api
> Get routes openapi

- api/v1/paths/data/csv.js
- api/v1/paths/data/file.js
- api/v1/paths/data/files.js
- api/v1/paths/elasticsearch/query.js
Try to fix https://gt.tsf.logilab.fr/tsf/issues/41?project=1
> fix(api): success and error are two distinct paths

- public/vocables/js/common.js
- public/vocables/js/sparqlProxies/sparql_OWL.js
- public/vocables/js/sparqlProxies/sparql_proxy.js
- public/vocables/js/tools/KGpropertyFilter.js
- public/vocables/js/tools/Standardizer.js
- public/vocables/js/tools/lineage/lineage_blend.js
- public/vocables/js/tools/lineage/lineage_classes.js
- public/vocables/js/tools/lineage/lineage_decoration.js
- public/vocables/js/tools/lineage/lineage_dictionary.js
- public/vocables/js/tools/sourceBrowser.js
- public/vocables/snippets/KGpropertyFilter/leftPanel.html
- public/vocables/snippets/lineage/lineage.html
> Cf 01 07 22

- README.md
- api/v1/paths/profiles.js
- api/v1/paths/sources.js
- api/v1/paths/users.js
- api/v1/paths/utils.js
- config_templates/profiles.json.default
- sort sources, users and profiles
> Improve configEditor

- mainapp/src/Component/ProfilesTable.tsx
Je n'ai trouvé le tri que dans les profiles, je ne sais pas si je manque quelque chose ? Aussi je n'ai pas bien compris l'utilité de useMemo ici alors je l'ai laissé. Tu me diras si c'est toujours nécessaire :)
> perf(configEditor): remove client side sort

- bin/KG/CsvTripleBuilder..js
- package-lock.json
- public/vocables/js/sparqlProxies/sparql_OWL.js
- public/vocables/js/sparqlProxies/sparql_generic.js
- public/vocables/js/tools/lineage/lineage_combine.js
- public/vocables/js/tools/lineage/lineage_containers.js
- public/vocables/js/tools/lineage/lineage_sources.js
Correction of   bug in indexation
Improvement Containers and KGcreator
> Cf v2 5 12 2022

- mainapp/src/Component/ProfilesTable.tsx
- mainapp/src/Component/SourcesTable.tsx
- mainapp/src/Component/UsersTable.tsx
add checkboxes in multiple selects in configEditor
> Checkboxes

- api/v1/paths/sources/{id}.js
- mainapp/src/Component/ProfilesTable.tsx
- mainapp/src/Component/SourcesTable.tsx
- mainapp/src/Component/UsersTable.tsx
- mainapp/src/Source.ts
- use tsv instead of csv to avoid conflict with comma in sparql topClasses
- display groups in tsv user export
- fix delete source
> Fix config editor

- api/v1/paths/health.js
```
curl -q http://localhost:3010/api/v1/health
{"health":{"virtuoso":true,"elasticsearch":true,"spacyserver":true,"sqlserver":true}}
```
> feat(api): add health route

- README.md
According to this issue #256 
Update to the readme file for the installation of Souslesens
> Edit Read me file

- .gitignore
- bin/configManager..js
- bin/www
- jena/RDF2triples.java
- model/config.js
- public/vocables/js/commonUIwidgets.js
- public/vocables/js/sparqlProxies/sparql_CRUD.js
- public/vocables/js/sparqlProxies/sparql_OWL.js
- public/vocables/js/sparqlProxies/sparql_common.js
- public/vocables/js/sparqlProxies/sparql_generic.js
- public/vocables/js/tools/lineage/lineage_classes.js
- public/vocables/js/tools/lineage/lineage_relationFilter.js
- public/vocables/js/tools/lineage/lineage_relations.js
- public/vocables/js/tools/lineage/lineage_sources.js
- public/vocables/js/tools/sourceBrowser.js
- public/vocables/snippets/lineage/relationsDialog.html
implement saevd queris in Lineage_relations.js
> Cf v3 20 03 23

- README.md
- api/v1/paths/profiles.js
- scripts/remove_admin_profile_migration.js
as an admin has full right on all ressources in a hard-codded way, don't store an admin profile in configuration, but use a hard-codded admin profile too.
> Remove admin profile from profiles.json

- api/v1/paths/copygraph.js
- api/v1/paths/getontologyrooturis.js
- api/v1/paths/httpProxy.js
- api/v1/paths/importsource.js
- api/v1/paths/shortestPath.js
- app.js
- public/vocables/js/tools/admin.js
- public/vocables/js/tools/lineage/lineage_graphTraversal.js
- public/vocables/ontocommons/ontocommons.js
Create API routes:
- Shortestpath
- copygraph
- importsource
from httpproxy
> Move HTTPProxy to dedicated API routes

- mainapp/package-lock.json
- mainapp/package.json
- mainapp/src/Admin.tsx
- mainapp/src/Component/ProfilesTable.tsx
- mainapp/src/Component/SourcesTable.tsx
- mainapp/src/Component/errorMessage.tsx
- mainapp/src/Profile.ts
- mainapp/src/Source.ts
This MR adds zod to validate profiles and sources forms
> Add validation to form

- mainapp/src/Component/SourcesTable.tsx
- mainapp/src/Source.ts
I stumbled into this error when I tried to fetch data: [ { "code": "invalid_type", "expected": "string", "received": "null", "path": [ "graphUri" ], "
> roll back to oldprevious mainapp because bug

- public/vocables/config/app_config.js
- public/vocables/modules/graph/VisjsGraphClass.js
- public/vocables/modules/shared/ontologyModels.js
- public/vocables/modules/tools/lineage/lineage_sources.js
- public/vocables/snippets/lineage/lineageAddEdgeDialog.html
- public/vocables/snippets/lineage/lineageLeftPanel.html
add disabled buttons capability  in lineage_sources.js and app_config.js
fixed clear last in VisjsGraphClass.js
> add disabled buttons capability  in lineage_sources.js and app_config.js

- mainapp/src/Component/ProfilesTable.tsx
- mainapp/src/Component/UsersTable.tsx
- mainapp/src/Profile.ts
- model/profiles.js
- model/sources.js
> Bug fixes and improvments

- model/profiles.js
- model/sources.js
> Fix edit profiles

- api/v1/paths/elasticsearch/clean.js
- api/v1/paths/elasticsearch/indices.js
- api/v1/paths/sparql/graphs.js
- mainapp/src/Admin.tsx
- mainapp/src/Component/SourcesTable.tsx
- mainapp/src/Source.ts
- model/index.js
- model/rdfData.js
- package-lock.json
- package.json
- tests/data/config/mainConfig.json
> Display green/red circle if source have/don't have a rdf graph and elasticsearch indices

- bin/userRequestFiltering..js
- public/vocables/modules/sparqlProxies/sparql_common.js
- public/vocables/modules/sparqlProxies/sparql_generic.js
- public/vocables/modules/tools/KGcreator.js
- public/vocables/modules/tools/lineage/lineage_axioms_draw.js
- public/vocables/modules/tools/lineage/lineage_containers.js
- public/vocables/modules/tools/lineage/lineage_properties.js
- public/vocables/modules/uiWidgets/nodeInfosWidget.js
> fix NodesInfos edit

- README.md
- package-lock.json
- package.json
- release-new.sh
> WIP: feat: add CHANGELOG.md

- public/vocables/config/app_config.js
- public/vocables/modules/sparqlProxies/sparql_OWL.js
- public/vocables/modules/uiWidgets/KGqueryWidget.js
- public/vocables/snippets/lineage/lineageRightPanel.html
- Desactivate some language
- Add skos in the dictionary langage
> Fix minors bugs elastic search and desactivate mappings and rules button

- CHANGELOG.md
- mainapp/src/Component/UsersTable.tsx
> refactor: replace groups in the Users table with profiles

- CHANGELOG.md
- mainapp/src/Component/ProfilesTable.tsx
- mainapp/src/Component/SourcesTable.tsx
- mainapp/src/Profile.ts
- mainapp/src/Source.ts
> fix: disable name field when editing source/profile

- CHANGELOG.md
- mainapp/src/Source.ts
> fix(configEditor): group cannot start with /

- app.js
- bin/util..js
- mainapp/src/graph-management.tsx
- model/users.js
> feat(app): add the x-token header management to /api routes

- api/v1/paths/rdf/graph.js
> fix: uncomment import of os module

- public/vocables/responsive/widget/html/botResponsive.html
> small improvements

- api/v1/api-doc.js
- api/v1/paths/sources.js
- api/v1/paths/users/theme.js
- mainapp/src/Component/ProfilesTable.tsx
- model/profiles.js
- public/vocables/responsive/responsiveUI.js
- scripts/migrations/migration_1.56_profiles.js
> feat: associate a theme with a profile

- model/profiles.js
- tests/data/config/mainConfig.json
- tests/model.profiles.test.js
> fix(model): always return the mainConfig default theme with the /users/theme route

- api/v1/paths/sources.js
- model/users.js
> fix(sources): do not allow source creation for user without authorization

- docker-compose.dev.yaml
- docker-compose.yaml
> chore: use postgis image instead of postgres

- mainapp/src/Component/SourcesTable.tsx
- mainapp/src/Source.ts
- mainapp/src/graph-management.tsx
- **feat(graphManagement): use mui table with sorting**
- **fix: remove console.log**
- **feat(configEditor): sort sources by graphURI and Groups**
fixes #615
fixes #601
fixes #643
> Sort GraphManagemnent + sort sources by graphURI and groups

- mainapp/src/Component/DatabasesTable.tsx
This identifier can be clicked to store it in the system clipboard.
> feat(ConfigEditor): show the database identifier in the table

- mainapp/src/graph-management.tsx
These errors (generally network errors) are then shown in the modal.
Closes #701
> Catch unexpected errors during upload/download

- mainapp/src/graph-management.tsx
> feat(GraphManagement): stop progressing to 100% inconditionally on download

- mainapp/package.json
- mainapp/src/Admin.tsx
- mainapp/src/Component/DatabasesTable.tsx
- mainapp/src/Component/LogsTable.tsx
- mainapp/src/Component/SourcesTable.tsx
- mainapp/src/Source.ts
- mainapp/src/Utils.ts
- mainapp/src/graph-management.tsx
- model/rdfData.js
- package-lock.json
- **fix(ConfigEditor): add the missing identifier header in DatabasesTable**
- **fix(ConfigEditor): do not crash when select the Source tab again**
- **style(ConfigEditor): fix the typo on the notAsked strings**
- **chore(pkg): add human-number dependencies**
- **feat(configEditor): display graph size**
- **feat(graphManagement): display graph size**
- **feat(graphManagement): restore sorting table + add graph size sorting**
- **fix(graphManagement): restore searchbar**
> Show graph size

- .gitignore
- api/v1/paths/logs.js
- api/v1/paths/logs/{period}.js
- bin/logger..js
- mainapp/src/Admin.tsx
- mainapp/src/Component/LogsTable.tsx
- mainapp/src/Log.ts
- package-lock.json
- package.json
- scripts/migrations/migration_1.72_logrotate.js
closes #718 
- **feat(logging): rotate logs every month**
- **feat(migrations): migrate log files**
> Rotate winston logs

- docker-compose.yaml
> chore(docker-compose): persist whole data directory

- mainapp/src/Component/SourcesTable.tsx
> feat(configEditor): Do not allow to publish source in PRIVATE group

- mainapp/src/graph-management.tsx
- **chore(compose): expose isql port in dev stack**
- **feat(graphManagement): set chunk size to 50Mo**
> WIP: graphManagement: increase chunkSize

- README.md
> docs: document how to import sls modules from plugins

- public/vocables/config/tools.js
- public/vocables/modules/tools/KGquery/KGquery.js
- public/vocables/responsive/KGquery/html/KGqueryQueryTab.html
> feat(KGquery): Add a generic configuration to define links between tools

- Dockerfile
- api/v1/api-doc.js
- api/v1/paths/admin/all-tools.js
- api/v1/paths/auth/logout.js
- api/v1/paths/config.js
- api/v1/paths/health.js
- api/v1/paths/logs.js
- api/v1/paths/logs/{period}.js
- api/v1/paths/profiles.js
- api/v1/paths/rdf/graph.js
- api/v1/paths/sources.js
- api/v1/paths/users/{id}.js
- bin/authentication..js
- mainapp/src/Admin.tsx
- mainapp/src/Component/ConfigForm.tsx
- mainapp/src/Component/ProfilesTable.tsx
- mainapp/src/Config.ts
- mainapp/src/Profile.ts
- mainapp/src/Tool.ts
- model/ProfileTypes.ts
- model/ToolTypes.ts
- model/config.js
- model/mainConfig.js
- model/profiles.js
- model/sources.js
- model/tools.js
- public/vocables/config/tools.js
- tests/model.profiles.test.js
- tests/model.sources.test.js
> Configeditor settings tab

- README.md
> docs(plugin): communication from other tools

- model/tools.js
- public/vocables/modules/tools/KGquery/KGquery.js
- public/vocables/responsive/KGquery/html/KGqueryQueryTab.html
> fix(KGquery): Graph is a KG feature, not a tool

- mainapp/src/Component/DatabasesTable.tsx
- mainapp/src/Component/LogsTable.tsx
- mainapp/src/Component/PluginsForm.tsx
- mainapp/src/Component/ProfilesTable.tsx
- mainapp/src/Component/SourcesTable.tsx
- mainapp/src/Component/UsersTable.tsx
- mainapp/src/Utils.ts
Closes https://github.com/souslesens/souslesensVocables/issues/834
> feat(mainapp): replace filter autocomplete by input

- mainapp/src/Component/DatabasesTable.tsx
- mainapp/src/Component/SourcesTable.tsx
- mainapp/src/Utils.ts
Closes https://github.com/souslesens/souslesensVocables/issues/847
> feat(mainapp): add json download for sources and databases

- scripts/init_configs.js
> chore: init_configs create pluginsConfig.json

- app.js
- bin/authentication..js
- config_templates/mainConfig.json.default
- package-lock.json
- package.json
> feat: implements basic auth0 authentication with passport

- app.js
- model/SourceTypes.ts
Closes https://github.com/souslesens/souslesensVocables/issues/815
> feat(model): load default graph on start

- mainapp/src/Component/PluginsForm.tsx
By using the formJSON, the data were not correctly set in the repository object, causing repository, which migrate from the solo-plugin to multiple-plugins, to have missing attributes.
> fix(mainapp): use the repository object when updating Plugin Repository

- api/v1/paths/users/token.js
- mainapp/src/Component/UserProfile.tsx
- mainapp/src/Component/UserSources.tsx
- mainapp/src/Source.ts
- mainapp/src/Utils.ts
- mainapp/src/user-management.tsx
- public/vocables/modules/tools/UserManagement.js
> feat: settings allow users to update owned sources

- mainapp/src/Profile.ts
> fix(mainapp): do not raise a require error when editing a profile

- mainapp/src/graph-management.tsx
Closes https://github.com/souslesens/souslesensVocables/issues/873
> feat(mainapp): allow downloading graph management as csv

- api/v1/api-doc.js
- mainapp/src/Component/ProfilesTable.tsx
- mainapp/src/Profile.ts
- model/ProfileTypes.ts
- model/profiles.js
- scripts/migrations/migration_NEXT_refactor_allowedtools.js
- tests/data/config/profiles.json
- tests/data/config_templates/config_1/profiles.json
- tests/model.profiles.test.js
fixes #784
fixes #783
- Remove forbbidenTools
- AllowedTools is a list (remove the "ALL" keyword)
- Migrate data
> Refactor AllowedTools and forbiddenTools in profiles

- mainapp/package.json
- mainapp/src/Component/EditSourceDialog.tsx
- mainapp/src/Component/UserSources.tsx
- mainapp/vite.config.js
- package-lock.json
- public/vocables/index.html
- public/vocables/modules/tools/EditSourceDialog/EditSourceDialog.js
- public/vocables/modules/tools/lineage/lineage_sources.js
- tsconfig.json
> feat(lineage): add edit source dialog

- mainapp/src/Component/DownloadGraphModal.tsx
- mainapp/src/Component/UploadGraphModal.tsx
- mainapp/src/graph-management.tsx
- mainapp/vite.config.js
- public/vocables/index.html
- public/vocables/modules/bots/createSLSVsource_bot.js
- public/vocables/modules/tools/UploadGraphModal/UploadGraphModal.js
Based on https://github.com/souslesens/souslesensVocables/pull/895
Closes https://github.com/souslesens/souslesensVocables/issues/894
> Feat: share upload graph dialog

- mainapp/src/mappingModeler-upload-app.tsx
- mainapp/vite.config.js
- public/vocables/modules/bots/_botEngine.js
- public/vocables/modules/shared/UI.js
- public/vocables/modules/tools/KGcreator/KGcreator.js
- public/vocables/modules/tools/mappingModeler/mappingModeler.js
- public/vocables/modules/uiWidgets/css/Bot.css
- public/vocables/modules/uiWidgets/html/bot.html
- **botEngine chat**
- **Redraw technical mappings model**
- **mappingModeler continue**
> OK 11 10 2023

- mainapp/src/Component/SourcesDialog.tsx
> refactor(mainapp): modification on the Source form dialog

- mainapp/src/Component/SourcesDialog.tsx
- mainapp/src/Source.ts
- scripts/migrations/migration_NEXT_sources-add-prefix.js
- **feat(migrations): add prefix field in sources.json**
- **feat(mainapp): add prefix field on SourcesDialog**
- **fix(mainapp): set error string to helperText**
- **fix(mainapp): fix group validation**
- **fix(mainapp): handle predicates correctly**
> ConfigEditor: sourceForm: add prefix + various fixes

- bin/KGbuilder/KGbuilder_triplesMaker.js
- bin/util..js
- public/vocables/index.html
- public/vocables/modules/shared/export.js
- public/vocables/modules/tools/KGquery/KGquery.js
- public/vocables/modules/tools/axioms/nodeInfosAxioms.js
- public/vocables/modules/tools/mappingModeler/html/mappingModelerLeftPanel.html
- public/vocables/modules/tools/mappingModeler/mappingModeler.js
- public/vocables/modules/uiWidgets/nodeInfosWidget.js
- **mappingModeler mappings to KGcreator**
- **Fix KGquery from shacl modifs**
- **fix nodeInfosAxioms**
- **fix mappingTechnicalGraph**
> OK 17 10 2024

- mainapp/src/Component/EditSourceDialog.tsx
- mainapp/src/Component/SourcesTable.tsx
- mainapp/src/Source.ts
- mainapp/src/index.tsx
Ensure to update the sources map from this constant when a source was added, updated or removed from the ConfigEditor.
> feat(mainapp): reload the sources in the window.Config constant

- .github/workflows/test-default-config.yaml
- app.js
- config_templates/mainConfig.json.default
- model/config.js
- scripts/test_config_template.js
- tests/data/config/mainConfig.json
> feat(express): use zod to validate the mainConfig.json at startup

- public/vocables/modules/shared/UI.js
- public/vocables/modules/shared/styles.less
> feat(public/vocables): sort tools selector from the tools_available field

- api/v1/paths/admin/plugins/repositories/fetch/{id}.js
- api/v1/paths/admin/plugins/repositories/repository/{id}.js
- mainapp/src/Component/PluginsForm.tsx
- mainapp/src/Plugins.ts
- model/tools.js
> fix(mainapp): improve the error banner when a repository cannot be fetched

- mainapp/src/Component/DownloadGraphModal.tsx
- mainapp/src/Component/UploadGraphModal.tsx
> feat(mainapp): catch sls-api errors

- docker-compose.yaml
- docs/docs/configuration/jowl.md
- docs/docs/configuration/sls-py-api.md
- docs/docs/configuration/souslesens.md
- docs/docs/index.md
- docs/docs/installation/install-a-development-instance.md
- docs/docs/installation/sls-py-api.md
- **docs: sls-py-api configuration**
- **docs: jowl configuration**
- **docs: rename configuration files**
> sls-py-api and jowl documentation

- mainapp/src/Component/DatabasesTable.tsx
- mainapp/src/Component/LogsTable.tsx
- mainapp/src/Component/PluginsForm.tsx
- mainapp/src/Component/ProfilesTable.tsx
- mainapp/src/Component/SourcesTable.tsx
- mainapp/src/Component/UsersTable.tsx
- mainapp/src/graph-management.tsx
- **fix(mainapp): disable autocomplete on searchbars**
- **feat(graphManagement): standard searchbar**
> Searchbars improvement

- api/v1/paths/rdf/graph/metadata.js
- docker-compose.dev.yaml
- mainapp/package.json
- mainapp/src/Component/MetadataModal.tsx
- mainapp/src/Source.ts
- mainapp/src/graph-management.tsx
- model/rdfData.js
- package-lock.json
- **chore(dev): disable virtuoso timeouts**
- **feat(api): GET and POST metadata**
- **chore: upgrade mui-x-data-grid to 7**
- **feat(mainapp/graphManagement): display metadata modal**
> Metadata editor

- mainapp/src/Component/ProfilesTable.tsx
> feat: add filter to source control access

- api/v1/paths/logs.js
- api/v1/paths/logs/{period}.js
- bin/logger..js
- config_templates/mainConfig.json.default
- docs/docs/configuration/souslesens.md
- mainapp/src/Component/LogsTable.tsx
- mainapp/src/Component/ProfilesTable.tsx
- model/config.js
- scripts/migrations/migration_NEXT_add_baseUri_in_sources.js
- tests/data/config/mainConfig.json
- **feat(config): replace the logDir option with a logs object**
- **feat(bin): adapt the logger with the new logs section in mainConfig**
- **feat(api): adapt the /log routes to not use the symlink**
Related to #1147
> feat: allow to configure the logger system on SousLeSens

- model/__mocks__/utils.js
- model/profiles.js
- model/userData.js
- model/users.js
- package-lock.json
- package.json
- tests/data/database/profiles.json
- tests/data/database/userData.json
- tests/data/database/users.json
- tests/model.profiles.test.js
- tests/model.userData.test.js
- tests/model.users.test.js
- **test: add a new mock for using sqlite with the model testing**
- **test: rewrite model/profiles tests to use sqlite**
- **test: rewrite model/users tests to use sqlite**
- **test: rewrite model/userData tests to use sqlite**
> test: use sqlite with the tests instead of mocking requests

- mainapp/src/Component/SourcesDialog.tsx
> feat: add a create source with upload graph button

- api/v1/paths/admin/users.js
- mainapp/src/Component/UsersTable.tsx
- mainapp/src/User.ts
https://github.com/souslesens/souslesensVocables/issues/1182
> Prevent sending empty password on user form

- mainapp/src/Component/PasswordField.tsx
- mainapp/src/Component/UsersTable.tsx
https://github.com/souslesens/souslesensVocables/issues/1182
> refactor: use zod to validate user form

- bin/authentication..js
> fix(authentication): create use account if not exists when first login with keycloak

- api/v1/paths/profiles.js
- api/v1/paths/users.js
- model/users.js
- **fix(model/user): isAdmin always return true if auth is disabled**
- **feat(api/users): /users return all users if user is admin**
- **feat(api/users): /profiles return all profiles if user is admin**
> improve API /users and /profiles for admin

- mainapp/src/graph-management.tsx
- **feat(mainapp): add the Group column to GraphManagement** #1359
- **feat(mainapp): add the Triple unit for the Graph Size column in GraphManagement** #1360
> feat: add two modification on the GraphManagement tool

- api/v1/paths/users/data.js
- api/v1/paths/users/data/{id}/exec.js
- docs/docs/api/index.md
- docs/docs/api/userdata.md
- docs/docs/index.md
- docs/docs/userdoc/index.md
- **fix(api): add id to API doc**
- **fix(api): users/data/{id}/exec if no params are passed**
- **docs: add UserData documentation**
> UsersData documentation
